ARG BASE_OS
FROM $BASE_OS as runtime

ARG NAME
ARG PACKAGENAME
ARG PROCESS_NAME
ARG HOMEDIR="/home/${NAME}"
ENV PATH=$HOMEDIR/$PROCESS_NAME/bin:$PATH
ENV LD_LIBRARY_PATH=$HOMEDIR/$PROCESS_NAME/lib:$LD_LIBRARY_PATH

#RUN mkdir /lib64
#RUN ln -s /lib/libc.musl-x86_64.so.1 /lib64/ld-linux-x86-64.so.2

# Copy the binaries.
WORKDIR $HOMEDIR
COPY  pkg/${PACKAGENAME} ./
COPY  pkg/alpine-glibc/glibc-2.33-r0.apk  ./
RUN apk add --allow-untrusted glibc-2.33-r0.apk
RUN tar -zxvf ${PACKAGENAME}  
RUN sed -i 's/dl-cdn.alpinelinux.org/mirrors.tuna.tsinghua.edu.cn/g' /etc/apk/repositories;
COPY ./entrypoint/entrypoint.sh /
RUN  chmod 775 /entrypoint.sh

# Add the entrypoint.
WORKDIR $HOMEDIR
ENTRYPOINT ["/entrypoint.sh"]
CMD ["help"]
