apiVersion: idx.inspur.com/v1alpha1
kind: FileSync
metadata:
  name: example-mini
spec:
  global:
    mq: NATS
  nats:
    ip: "nats-edge.default.svc.cluster.local"
    port: 4222
  reader:
    nodeSelector: 
      kubernetes.io/hostname: centos78-0
    image: "filereader:8.1.0-arm"
    srcPath: "/example-mini/src"    # 没有配置 PVC 时，使用 hostpath
    dataTopic: "example"            # streamName
    dataSliceSize: "1m"
    fmodeRead: 0
    userRead: 0
    logsyncMode: 0
  writer:
    nodeSelector: 
      kubernetes.io/hostname: centos78-1
    image: "filewriter:8.1.0-20210527-centos"
    dataTopic: "example.example"          # means streamName.consumerName. streamName and consumerName should be the same
    rcvPath: "/example-mini/rcvCreds"     # 没有配置 PVC 时，使用 hostpath
    fmodeWrite: 0
    userWrite: 0
